# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/AlekSi/pointer"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go-sourcepath"

[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/config"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/database"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/go-echarts"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/logger"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/machine"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/nvidia-smi"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/parallel"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/tracer"

[[constraint]]
  branch = "master"
  name = "github.com/c3sr/utils"

[[constraint]]
  name = "github.com/cheekybits/genny"
  version = "1.0.0"

[[constraint]]
  name = "github.com/chewxy/math32"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.1.0"

[[constraint]]
  name = "github.com/getlantern/deepcopy"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/snappy"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/ianlancetaylor/demangle"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "3.0.7"

[[constraint]]
  name = "github.com/levigross/grequests"
  version = "0.10.0"

[[constraint]]
  name = "github.com/mailru/easyjson"
  version = "0.7.6"

[[constraint]]
  name = "github.com/mattn/go-zglob"
  version = "0.0.3"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  branch = "master"
  name = "github.com/ready-steady/sort"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=0.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  name = "github.com/uber/jaeger"
  version = "1.21.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "upper.io/db.v3"
  version = "3.7.1"

[prune]
  go-tests = true
  unused-packages = true
